name: CI/CD

# Workflow triggers: Pushes to master, any tag, or pull requests to master
on:
  push:
    branches: ["master"]
    tags: ["*"]
  pull_request:
    branches: ["master"]

# Ensure only one workflow run per ref, canceling in-progress runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Define default settings and environment variables
env:
  PYTHON_VERSION: "3.13"
defaults:
  run:
    working-directory: .

# Reusable step templates
steps:
  &checkout-step
    - name: Checkout repository
      uses: actions/checkout@v4

  &setup-uv-step
    - name: Set up UV and Python
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        enable-cache: true

# Development Jobs
# --------------------------------
jobs:
  # Lint job: Runs linters, skipped on tag pushes
  lint:
    runs-on: ubuntu-24.04
    if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
    steps:
      - *checkout-step
      - *setup-uv-step
      - name: Sync UV dependencies for lint
        run: uv sync --frozen --group lint

  # Test job: Runs tests in parallel across multiple Python versions, skipped on tag pushes
  test:
    runs-on: ubuntu-24.04
    needs: lint
    strategy:
      fail-fast: false  # Continue even if one version fails
      matrix:
        python-version: [ "3.9", "3.12", "3.13" ]  # Parallel test jobs
    steps:
      - *checkout-step
      - name: Set up UV and Python for test matrix
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Sync UV dependencies for test
        run: uv sync --frozen --group lint --group test
      - name: Run pytest
        run: uv run pytest -q

  # Build job: Builds the project, skipped on non-tag pushes
  build:
    runs-on: ubuntu-24.04
    needs: test
    if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
    steps:
      - *checkout-step
      - *setup-uv-step
      - name: Sync UV dependencies for build
        run: uv sync --frozen
      - name: Build project
        run: uv build
      - name: Upload dist artifacts (only on tag pushes)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  # Docs job: Builds documentation, skipped on tag pushes
  docs:
    runs-on: ubuntu-24.04
    needs: lint
    if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
    steps:
      - *checkout-step
      - *setup-uv-step
      - name: Sync UV dependencies for docs
        run: uv sync --frozen --group docs
      - name: Build MkDocs documentation
        run: uv run mkdocs build --config-file mkdocs.yaml
        working-directory: .config

  # Release Jobs
  # --------------------------------

  # Release job: Creates GitHub release, runs only on tag pushes
  release:
    runs-on: ubuntu-24.04
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - *checkout-step
      - name: Create GitHub release
        uses: asimov-platform/release-action@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          changelog-path: CHANGES.md
          compute-checksum: false

  # Publish job: Publishes to PyPI, runs only on tag pushes
  publish:
    runs-on: ubuntu-24.04
    needs: release
    steps:
      - *checkout-step
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
        continue-on-error: true
      - *setup-uv-step
      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: echo "Hello world"
#        run: uv publish --token $UV_PUBLISH_TOKEN dist/*

